{
 "title": "http-server-projeto-korp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_up", "legendFormat": "status" }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Requisições no /projeto-korp",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{path=\"/projeto-korp\"})",
     "legendFormat": "/projeto-korp"
    }
   ]
  },
  {
   "title": "Taxa de Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{path=\"/projeto-korp\"}[1m])",
     "legendFormat": "/projeto-korp"
    },
    {
     "expr": "rate(http_requests_total{path=\"/health\"}[1m])",
     "legendFormat": "/health"
    }
   ]
  },
  {
   "title": "Requisições Acumuladas por Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 8, "h": 7 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Divisão por Endpoint",
   "type": "piechart",
   "gridPos": { "x": 8, "y": 12, "w": 4, "h": 7 },
   "targets": [
    {
     "expr": "sum by (path) (http_requests_total)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}